#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used
LOWLEVEL= $(ROOT)lowlevel
MIDLEVEL = $(ROOT)midlevel
HIGHLEVEL= $(ROOT)highlevel
SUBHIGH = 
SUBMID = 
# Lists of *.c
# HL_LIBS is for files that do not reference stm32 files, etc.
HL_LIBS = 
# HARDWARE_LIBS include files that reference stm32 files
HARDWARE_LIBS = 

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

#USB
HARDWARE_LIBS += $(LOWLEVEL)/usbhid-target.c
HARDWARE_LIBS += $(LOWLEVEL)/usb.c


#other
HARDWARE_LIBS += $(LOWLEVEL)/analogMux.c



# Bit operators
HL_LIBS += $(MIDLEVEL)/bitoperators.c
HL_LIBS += $(MIDLEVEL)/buttonProc.c







# Join all the include folders together
INCLUDE_FOLDERS = $(LOWLEVEL) $(MIDLEVEL) $(HIGHLEVEL) $(SUBHIGH) $(SUBMID) $(HARDWARE_INCLUDE_DIR)
