#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

HL_LIBS += usbhid-target.c




#HL_LIBS += $(ROOT)configuration.c

#HL_LIBS += $(LOWLEVEL)/i2cSlave.c
#HL_LIBS += $(LOWLEVEL)/i2cMaster.c
#HL_LIBS += $(LOWLEVEL)/serial.c
#HL_LIBS += $(LOWLEVEL)/mt9m001.c
#HL_LIBS += $(LOWLEVEL)/sdram.c

#general things
#HL_LIBS += $(MIDLEVEL)/commandHandler.c
#HL_LIBS += $(MIDLEVEL)/polarCart.c
#HL_LIBS += $(MIDLEVEL)/axsAng.c


#centroiding phase
#SUBHIGH += $(HIGHLEVEL)/cent
#HL_LIBS += $(HIGHLEVEL)/cent/centroiding.c

#star ID phase
#SUBHIGH += $(HIGHLEVEL)/starID
#HL_LIBS += $(HIGHLEVEL)/starID/starID.c
#HL_LIBS += $(HIGHLEVEL)/starID/kVectorData.c
#HL_LIBS += $(HIGHLEVEL)/starID/kVectorSearch.c
#HL_LIBS += $(HIGHLEVEL)/starID/probDataAssoc.c
#HL_LIBS += $(HIGHLEVEL)/starID/triangleAngle.c


#Attitude estimation phase
#SUBHIGH += $(HIGHLEVEL)/attEst
#HL_LIBS += $(HIGHLEVEL)/attEst/attEst.c
#HL_LIBS += $(HIGHLEVEL)/attEst/bnb.c
#HL_LIBS += $(HIGHLEVEL)/attEst/cube.c
#HL_LIBS += $(HIGHLEVEL)/attEst/pqueue.c

#DK matrix libs
#SUBMID += $(MIDLEVEL)/DK
#HL_LIBS += $(MIDLEVEL)/DK/vec.c
#HL_LIBS += $(MIDLEVEL)/DK/mat.c
