#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

#USB
HL_LIBS += $(LOWLEVEL)/usbhid-target.c
HL_LIBS += $(LOWLEVEL)/usb.c


#other
HL_LIBS += $(LOWLEVEL)/analogMux.c



# Bit operators
HL_LIBS += $(MIDLEVEL)/bitoperators.c
HL_LIBS += $(MIDLEVEL)/buttonProc.c